import type { Listing, Seller } from "@/lib/types";

const sellers: Seller[] = [
  {
    id: "seller-1",
    name: "Alex R.",
    avatar: "https://i.pravatar.cc/150?u=seller-1",
    rating: 4.8,
    reviews: 124,
    isVerified: true,
  },
  {
    id: "seller-2",
    name: "Samantha B.",
    avatar: "https://i.pravatar.cc/150?u=seller-2",
    rating: 4.9,
    reviews: 88,
    isVerified: true,
  },
  {
    id: "seller-3",
    name: "TechDeals",
    avatar: "https://i.pravatar.cc/150?u=seller-3",
    rating: 4.5,
    reviews: 210,
    isVerified: false,
  },
];

export const listings: Listing[] = [
  {
    id: "1",
    title: "iPhone 14 Pro, 256GB, Deep Purple",
    brand: "Apple",
    model: "iPhone 14 Pro",
    variant: { ram: 6, storage: 256, color: "Deep Purple" },
    price: 75000,
    isNegotiable: true,
    condition: "like_new",
    description: "Mint condition iPhone 14 Pro. No scratches or dents. Battery health at 95%. Comes with original box and cable.",
    images: ["listing-1", "listing-4"],
    location: { city: "Bengaluru", state: "Karnataka", lat: 12.9716, lon: 77.5946 },
    purchaseYear: 2022,
    seller: sellers[0],
    isBoosted: true,
    viewCount: 1204,
    favoriteCount: 89,
    createdAt: "2024-07-18T10:00:00Z",
    status: 'active',
  },
  {
    id: "2",
    title: "Samsung Galaxy S23 Ultra, 512GB",
    brand: "Samsung",
    model: "Galaxy S23 Ultra",
    variant: { ram: 12, storage: 512, color: "Phantom Black" },
    price: 82000,
    isNegotiable: false,
    condition: "new",
    description: "Brand new, sealed pack Galaxy S23 Ultra. Unwanted gift. Indian unit with full warranty.",
    images: ["listing-2", "listing-7"],
    location: { city: "Mumbai", state: "Maharashtra", lat: 19.0760, lon: 72.8777 },
    purchaseYear: 2023,
    seller: sellers[1],
    isBoosted: true,
    viewCount: 980,
    favoriteCount: 112,
    createdAt: "2024-07-20T12:30:00Z",
    status: 'active',
  },
  {
    id: "3",
    title: "Google Pixel 7, 128GB, Obsidian",
    brand: "Google",
    model: "Pixel 7",
    variant: { ram: 8, storage: 128, color: "Obsidian" },
    price: 38000,
    isNegotiable: true,
    condition: "good",
    description: "Well-maintained Pixel 7. Excellent camera. Minor signs of use on the frame. Screen is perfect. No box.",
    images: ["listing-3", "listing-11"],
    location: { city: "Delhi", state: "Delhi", lat: 28.7041, lon: 77.1025 },
    purchaseYear: 2022,
    seller: sellers[2],
    isBoosted: false,
    viewCount: 2500,
    favoriteCount: 230,
    createdAt: "2024-07-15T09:00:00Z",
    status: 'active',
  },
  {
    id: "4",
    title: "OnePlus 11, 16GB RAM, 256GB",
    brand: "OnePlus",
    model: "11",
    variant: { ram: 16, storage: 256, color: "Titan Black" },
    price: 45000,
    isNegotiable: false,
    condition: "like_new",
    description: "Barely used OnePlus 11. Super fast performance and charging. Full kit available.",
    images: ["listing-5", "listing-6"],
    location: { city: "Chennai", state: "Tamil Nadu", lat: 13.0827, lon: 80.2707 },
    seller: sellers[0],
    isBoosted: false,
    viewCount: 750,
    favoriteCount: 55,
    createdAt: "2024-07-19T18:00:00Z",
    status: 'active',
  },
  {
    id: "5",
    title: "iPhone 13, 128GB, Blue",
    brand: "Apple",
    model: "iPhone 13",
    variant: { ram: 4, storage: 128, color: "Blue" },
    price: 42000,
    isNegotiable: true,
    condition: "good",
    description: "Good condition iPhone 13. Battery health 88%. Minor scuffs on the side, screen is pristine with protector since day 1.",
    images: ["listing-5", "listing-12"],
    location: { city: "Pune", state: "Maharashtra", lat: 18.5204, lon: 73.8567 },
    purchaseYear: 2021,
    seller: sellers[1],
    isBoosted: false,
    viewCount: 1800,
    favoriteCount: 150,
    createdAt: "2024-07-17T14:20:00Z",
    status: 'active',
  },
  {
    id: "6",
    title: "Samsung Galaxy Z Fold 4, 256GB",
    brand: "Samsung",
    model: "Galaxy Z Fold 4",
    variant: { ram: 12, storage: 256, color: "Graygreen" },
    price: 65000,
    isNegotiable: true,
    condition: "good",
    description: "Galaxy Z Fold 4, one year old. Inner screen has a very light crease which is normal. No other issues.",
    images: ["listing-9", "listing-3"],
    location: { city: "Hyderabad", state: "Telangana", lat: 17.3850, lon: 78.4867 },
    purchaseYear: 2022,
    seller: sellers[2],
    isBoosted: false,
    viewCount: 630,
    favoriteCount: 40,
    createdAt: "2024-07-20T11:00:00Z",
    status: 'sold',
  },
  {
    id: "7",
    title: "Google Pixel 6a, 128GB, Charcoal",
    brand: "Google",
    model: "Pixel 6a",
    variant: { ram: 6, storage: 128, color: "Charcoal" },
    price: 22000,
    isNegotiable: false,
    condition: "like_new",
    description: "Pixel 6a, just 6 months old. Perfect budget camera phone. Not a single scratch. With box and bill.",
    images: ["listing-1", "listing-4"],
    location: { city: "Kolkata", state: "West Bengal", lat: 22.5726, lon: 88.3639 },
    purchaseYear: 2023,
    seller: sellers[0],
    isBoosted: false,
    viewCount: 3200,
    favoriteCount: 280,
    createdAt: "2024-07-12T20:00:00Z",
    status: 'active',
  },
  {
    id: "8",
    title: "iPhone 12, 64GB, Black - For parts",
    brand: "Apple",
    model: "iPhone 12",
    variant: { ram: 4, storage: 64, color: "Black" },
    price: 12000,
    isNegotiable: true,
    condition: "fair",
    description: "iPhone 12 with a cracked screen and back. Motherboard and other components are working fine. Good for parts or repair.",
    images: ["listing-8", "listing-10"],
    location: { city: "Bengaluru", state: "Karnataka", lat: 12.9716, lon: 77.5946 },
    purchaseYear: 2020,
    seller: sellers[2],
    isBoosted: false,
    viewCount: 950,
    favoriteCount: 30,
    createdAt: "2024-07-21T08:00:00Z",
    status: 'sold',
  },
];
