'use client';
// This file is automatically generated by Firebase Studio.
// Do not edit manually.

import {FirebaseProvider, initializeFirebase} from '@/firebase';
import type {ReactNode} from 'react';

/**
 * Initializes Firebase on the client and provides the Firebase context.
 * This ensures that Firebase is only initialized once.
 */
export function FirebaseClientProvider({children}: {children: ReactNode}) {
  const {app, auth, firestore} = initializeFirebase();

  return (
    <FirebaseProvider app={app} auth={auth} firestore={firestore}>
      {children}
    </FirebaseProvider>
  );
}
