'use client';
// This file is automatically generated by Firebase Studio.
// Do not edit manually.

import {FirebaseProvider, initializeFirebase} from '@/firebase';
import type {ReactNode} from 'react';
import { useEffect } from 'react';
import { useAuth } from './provider';
import { getFirebaseConfig } from './config';
import { FirebaseConfigError } from '@/components/FirebaseConfigError';

function SessionHandler() {
  const auth = useAuth();
  
  useEffect(() => {
    const handleAuthChange = async (user: any) => {
      if (user) {
        const idToken = await user.getIdToken();
        await fetch('/api/auth/session', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ idToken }),
        });
      } else {
        await fetch('/api/auth/session', { method: 'DELETE' });
      }
    };
    
    const unsubscribe = auth.onIdTokenChanged(handleAuthChange);
    return () => unsubscribe();
  }, [auth]);

  return null;
}

/**
 * Validates the Firebase configuration.
 * @returns {boolean} True if the configuration is valid, false otherwise.
 */
function isConfigValid(): boolean {
    const config = getFirebaseConfig();
    return !!(
        config.databaseURL &&
        !config.databaseURL.includes('YOUR_DATABASE_URL_HERE')
    );
}

/**
 * Initializes Firebase on the client and provides the Firebase context.
 * This ensures that Firebase is only initialized once.
 * It will render an error screen if Firebase is not configured correctly.
 */
export function FirebaseClientProvider({children}: {children: ReactNode}) {
  if (!isConfigValid()) {
      return <FirebaseConfigError />;
  }

  const {app, auth, firestore, database} = initializeFirebase();

  return (
    <FirebaseProvider app={app} auth={auth} firestore={firestore} database={database}>
      <SessionHandler />
      {children}
    </FirebaseProvider>
  );
}
