// This file is automatically generated by Firebase Studio.
// Do not edit manually.

/** The context associated with a Firestore security rule denial. */
export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  requestResourceData?: any;
};

/** A custom error for Firestore permission denials. */
export class FirestorePermissionError extends Error {
  constructor(public readonly context: SecurityRuleContext) {
    super(
      'FirestoreError: Missing or insufficient permissions: ' +
        `The following request was denied by Firestore Security Rules:\n${JSON.stringify(
          context,
          null,
          2
        )}`
    );
  }
}
