// This file is automatically generated by Firebase Studio.
// Do not edit manually.

import {EventEmitter} from 'events';
import type {FirestorePermissionError} from './errors';

type Events = {
  'permission-error': (error: FirestorePermissionError) => void;
};

// Provides a NodeJS EventEmitter with typed events.
class TypedEventEmitter extends EventEmitter {
  emit<E extends keyof Events>(event: E, ...args: Parameters<Events[E]>) {
    return super.emit(event, ...args);
  }
  on<E extends keyof Events>(event: E, listener: Events[E]) {
    return super.on(event, listener);
  }
}

export const errorEmitter = new TypedEventEmitter();
