// This file is automatically generated by Firebase Studio.
// Do not edit manually.

import {getApp, getApps, initializeApp, type FirebaseApp} from 'firebase/app';
import {getAuth, type Auth} from 'firebase/auth';
import {getFirestore, type Firestore} from 'firebase/firestore';
import {getDatabase, type Database} from 'firebase/database';
import {getFirebaseConfig} from './config';

// Provides a singleton for the Firebase app instance.
function getFirebaseApp() {
  if (getApps().length) return getApp();
  const firebaseConfig = getFirebaseConfig();
  return initializeApp(firebaseConfig);
}

let auth: Auth;
let firestore: Firestore;
let database: Database;

/**
 * Initializes and returns Firebase services.
 * This function ensures that Firebase is initialized only once.
 */
export function initializeFirebase(): {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
  database: Database;
} {
  const app = getFirebaseApp();
  auth = getAuth(app);
  firestore = getFirestore(app);
  database = getDatabase(app);

  return {app, auth, firestore, database};
}

export * from './provider';
export * from './auth/use-user';
export * from './firestore/use-collection';
export * from './firestore/use-doc';
