'use client';
// This file is automatically generated by Firebase Studio.
// Do not edit manually.

import type {FirebaseApp} from 'firebase/app';
import type {Auth} from 'firebase/auth';
import type {Firestore} from 'firebase/firestore';
import {createContext, useContext, type ReactNode} from 'react';
import { FirebaseErrorListener } from '@/components/FirebaseErrorListener';

// The context for the Firebase app, auth, and firestore instances.
// The values are provided by the `FirebaseProvider` component.
const FirebaseContext = createContext<{
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
} | null>(null);

/**
 * Provides the Firebase app, auth, and firestore instances to its children.
 * Should be used at the root of the component tree.
 */
export function FirebaseProvider({
  children,
  ...props
}: {
  children: ReactNode;
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
}) {
  return (
    <FirebaseContext.Provider value={props}>
      <FirebaseErrorListener />
      {children}
    </FirebaseContext.Provider>
  );
}

/**
 * Returns the Firebase app, auth, and firestore instances.
 * Throws an error if used outside of a `FirebaseProvider`.
 */
export function useFirebase() {
  const context = useContext(FirebaseContext);
  if (!context) {
    throw new Error('useFirebase must be used within a FirebaseProvider');
  }
  return context;
}

/** Returns the Firebase app instance. */
export function useFirebaseApp() {
  return useFirebase().app;
}

/** Returns the Firebase auth instance. */
export function useAuth() {
  return useFirebase().auth;
}

/** Returns the Firebase firestore instance. */
export function useFirestore() {
  return useFirebase().firestore;
}
