'use client';
// This file is automatically generated by Firebase Studio.
// Do not edit manually.

import {useEffect} from 'react';
import {errorEmitter} from '@/firebase/error-emitter';

/**
 * Listens for Firestore permission errors and throws them as uncaught
 * exceptions. This is useful for development builds, as it surfaces security
 * rule denials in the Next.js error overlay.
 */
export function FirebaseErrorListener() {
  useEffect(() => {
    errorEmitter.on('permission-error', (error) => {
      // In development, uncaught exceptions are surfaced in the Next.js overlay.
      if (process.env.NODE_ENV === 'development') {
        setTimeout(() => {
          throw error;
        });
      }
    });
  }, []);
  return null;
}
